API 구현 : POST /calc/engravings
f-lab-edu/lo-gak-gye pull request #22
Opened 2024-01-14 11:34 UTC by ber01

해당 PR 에서는 POST /calc/engravings API를 구현하였습니다.

주요 내용은 아래와 같습니다.

- Request의 종류가 다양하여 분할, 정복하여 파싱할 수 있는 컨버터를 여러개 생성하였습니다.
- 컨버터가 제대로 작동하는지 검증하기 위한 테스트를 진행하였습니다.
- 컨버터의 반환값을 종합하여 최종 반환값을 위한 메서드를 생성하였습니다.
- 중복된 상수값들을 추상 클래스를 생성하여 관리하도록 리팩터링 하였습니다.

2024-01-15 07:55 UTC, f-lab-troy requested changes

2024-01-15 07:55 UTC, f-lab-troy commented on src/main/java/me/minkh/app/domain/engraving/CombatAttribute.java
> +        this.criticalHitRate += dto.getCriticalHitRate();
이 class는 멀티스레드 환경에서 작동하는지에 대해 고려해보고 동시성 문제가 있을 수 있는지도 생각해보면 좋습니다.

2024-01-15 07:55 UTC, f-lab-troy commented on src/main/java/me/minkh/app/domain/engraving/CombatAttribute.java
> +    private double criticalHitRate;
java float이나 double등에서 발생할 수 있는 소수점 오차에 대해 조사해보시고 대체할 타입을 알아보시길 추천합니다.

2024-01-15 07:55 UTC, f-lab-troy commented on src/main/java/me/minkh/app/service/LostArkConstants.java
> +public abstract class LostArkConstants {
이 class가 abstract일 이유가 있을까요?

2024-01-15 07:55 UTC, f-lab-troy commented on src/main/java/me/minkh/app/service/engraving/converter/ArtifactConverter.java
> +            case NIGHTMARE, SALVATION, DOMINION -> {
artifact가 확장될 수 있다면 0, 0, 0, 0과 같은 수치들도 설정으로 빼서 switch문을 없애고 일괄적으로 처리하는 것도 고려해볼 수 있습니다.

2024-01-15 07:55 UTC, f-lab-troy commented on src/main/java/me/minkh/app/service/engraving/converter/CombatStatsConverter.java
> +        return critical * 0.0357;
magic number들은 모두 상수처리해주는게 좋습니다.

2024-01-15 07:55 UTC, f-lab-troy commented on src/main/java/me/minkh/app/service/engraving/converter/ElixirConverter.java
> +        if (type.equals(VANGUARD)) {
이 MR에서 적용된 이와 비슷한 여러 if/else를 확장성있게 가져갈 수 있는 방법이 있을지 생각해보시길 추천드립니다.

2024-01-15 07:58 UTC, f-lab-troy commented
note:
- 한번 올리신 MR은 리뷰되기까지 추가 commit을 안해주시는게 좋습니다. (수정사항이 있으면 MR올리시기 전에 완전히 리뷰 후 올리시면 됩니다)
- 리뷰어를 위해 한개의 MR은 보통 바뀐 파일 수와 바뀐 라인 수를 제한하는게 좋습니다. (파일 5개이하, 총 바뀐 줄 수 100줄 이하)

2024-01-15 07:58 UTC, ber01 commented on src/main/java/me/minkh/app/service/LostArkConstants.java
> +public abstract class LostArkConstants {
9bb74d73ae602b0296a8169ba13c51a954a9f27f

`final` 클래스로 상속을 못하게 막은 뒤, `private` 생성자를 추가해 인스턴스화 하는 것을 제한해 주었습니다.

2024-01-15 08:01 UTC, ber01 commented
> note:
> 
> * 한번 올리신 MR은 리뷰되기까지 추가 commit을 안해주시는게 좋습니다. (수정사항이 있으면 MR올리시기 전에 완전히 리뷰 후 올리시면 됩니다)
> * 리뷰어를 위해 한개의 MR은 보통 바뀐 파일 수와 바뀐 라인 수를 제한하는게 좋습니다. (파일 5개이하, 총 바뀐 줄 수 100줄 이하)

네 알겠습니다. 용어가 헷갈려서 그런데, MR을 커밋이라고 받아들이면 될까요?

2024-01-15 08:02 UTC, f-lab-troy commented
MR (merge request) = PR (pull request) 같은 의미라고 보시면 됩니다.

2024-01-15 08:17 UTC, ber01 commented
아래처럼 진행하면 될까요?

1. PR 생성 (PR을 생성했는데, 추가 내용이 있을 경우 새로운 PR 생성)
2. 코드 리뷰
3. 코드 리뷰에 지적받은 내용을 수정 후 커밋
4. 리뷰어가 수정 부분 검토
5. O -> Resolve conversation
6. X -> 3번으로

2024-01-15 08:22 UTC, f-lab-troy commented
네, 맞습니다.
> PR을 생성했는데, 추가 내용이 있을 경우 새로운 PR 생성

보통은 추가 내용이 있을 것 같다면 첫 PR 자체를 생성안하는게 최선이지만 부득이한 이유로 추가 내용이 있다면 현재 PR을 닫고 다시 새로 올리는게 좋습니다.

2024-01-15 09:05 UTC, ber01 commented on src/main/java/me/minkh/app/service/engraving/converter/CombatStatsConverter.java
> +        return critical * 0.0357;
edc1cc41849f8b9345065b98f42f68aaa046dfdb

magic number를 상수 처리 하였습니다.

단위 조정을 위한 1이나 100같은 값들도 처리해야 할까요?

2024-01-15 10:00 UTC, ber01 commented on src/main/java/me/minkh/app/domain/engraving/CombatAttribute.java
> +    private double criticalHitRate;
조사하면서, 해당 기능을 개발할 때 계속 이상한 값이 나오던 이유를 알게 되었습니다.

부정확한 float과 double의 사용을 피하고 BigDecimal 사용하면 정확한 값을 도출할 수 있을 것 같습니다.

2024-01-15 11:32 UTC, ber01 commented on src/main/java/me/minkh/app/domain/engraving/CombatAttribute.java
> +    private double criticalHitRate;
@f-lab-troy 

멘토님, 학습 삼아 CombatAttribute에 존재하는 타입을 BigDecimal로 변경해보았습니다.

올바른 출력을 하는 것을 확인할 수 있었습니다.

- 기존에 `30.906000000000002` 형태로 출력되던 소수점이 `30.906` 형태로 올바르게 출력되는 걸 볼 수 있었습니다.

다만 변환에 생각보다 오랜 시간이 걸렸고, 가독성이 썩 좋지는 않아보입니다.

현재 서비스에서는 소숫점 자리의 정확성이 중요하진 않아 리팩토링은 하지 않고 학습 정도로 넘어가려 합니다.

2024-01-15 11:59 UTC, ber01 commented on src/main/java/me/minkh/app/domain/engraving/CombatAttribute.java
> +        this.criticalHitRate += dto.getCriticalHitRate();
94128703ad8a09529368444325eb939945e35dc8

동시성 문제가 발생하는 지, 확인하기 위해 테스트 코드를 작성하여 문제가 발생하는 지 확인하였고

성능에 큰 이슈를 주지 않을 것 같아 `synchronized` 키워드를 고려해 보았으나

락을 이용하지 않는 편이 나을 것 같아 `AtomicReference<Double>`을 이용하였습니다.

2024-01-15 13:37 UTC, ber01 commented on src/main/java/me/minkh/app/service/engraving/converter/ArtifactConverter.java
> +            case NIGHTMARE, SALVATION, DOMINION -> {
5e3d49913cb3aeaec09f034b619ccc51acdcb292

확장을 고려하여, 초기에 데이터 베이스에 수치들을 저장한 뒤 이름을 통해 값을 가져와 일괄적으로 처리하도록 변경하였습니다.

2024-01-15 16:09 UTC, ber01 commented on src/main/java/me/minkh/app/service/engraving/converter/ElixirConverter.java
> +        if (type.equals(VANGUARD)) {
6b70d8770b9d6970375d0f3c3b537c8eea586925

확장성을 고려하여 전략 패턴을 적용해 보았습니다.

2024-01-16 11:39 UTC, f-lab-troy approved these changes

2024-01-16 12:03 UTC, ber01 commented
멘토님, 남은 4개의 리뷰는 코멘트나 반응을 해주시진 않으셨는데 `approved` 해주셨으면 완료됐다고 생각하고 머지하면 될까요?

2024-01-16 14:14 UTC, f-lab-troy commented
네, 나머지 다 확인 후 approve 드렸습니다. 현재 상태로 merge 하셔도 좋습니다.

2024-01-16 14:56 UTC, merged